name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: beta.tex
      - uses: actions/upload-artifact@v2
        with:
          name: PDF
          path: beta.pdf
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download 
        uses: actions/download-artifact@v2
        with:
          name: PDF
      - name: Display structure of downloaded files
        run: |
          git commit
          git push
            

