name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: beta.tex
          latexmk_use_xelatex: true
      - name: Display structure of downloaded files
        run: |
          git config --global user.email "eric.welch@wallawalla.edu"
          git config --global user.name "eric-manning"
          git add beta.pdf
          git commit -m "Last updated at $(date)"
          git push
            

